#!/usr/bin/env bash
# install nginx web server
sudo apt-get update
sudo apt-get install nginx
sudo apt-get update nginx
sudo start nginx.service
sudo curl 52.90.165.160
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo curl 52.90.165.160
sudo service nginx restart