#!/usr/bin/env bash
# install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo curl 52.90.165.160
sudo service nginx restart