#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World" > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
sudo sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/; internal; }' /etc/nginx/sites-available/default
sudo service nginx restart