#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt -y install haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_web
    bind *:80
    default_backend rgw
backend rgw
    balance roundrobin
    server  server1 52.90.165.160 check
    server  server2 	52.201.255.107 check
EOT
sudo service haproxy restart