#!/usr/bin/env bash
#Nginx must be running on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/mysite.com /etc/nginx/sites-enabled/default
sudo service nginx reload